### ISSUE TITLE
Complete the Filtering Menu Logic

### ISSUE THREAD

**Issue by SirWellington** [BlackWholeLabs/BlackNectar-iOS#10]
Complete the Filtering Logic so that it actually works.
![Filter.png](https://zube.io/files/BlackSourceLabs/1e01f2786ccc351a048174b24232c310.png)

**Comment by kevintbradbury** [comment]
subtask of [Zube #7](https://zube.io/blacksourcelabs/blacknectar/c/7)

**Comment by SirWellington** [comment]
This has been sitting here for a while. Is this still in progress?

**Comment by cordhernandez** [comment]
As of now I would say that this is complete. Kevin was mainly working on this.

**Comment by SirWellington** [comment]
Looks like this branch was closed already. Moving this into done.
