### ISSUE TITLE
Improve Map Segue

### ISSUE THREAD

**Issue by SirWellington** [BlackWholeLabs/BlackNectar-iOS#101]
# WHAT
Right now the Map segues when the "Map" button is tapped, or when the user drags from the edge of the screen.

The transition should follow the user's finger as he/she drags.

# WHY
It is inconsistent behavior to have the back-segue behave one way, and the forward segue behave another. 
![IMG_3819.PNG](https://zube.io/files/BlackSourceLabs/c25ebaa809a0e075e9b5e673642953dd.png)

**Comment by cordhernandez** [comment]
+Fix issue that reloads the stores in tableView every time you transition from the mapView back to the tableView
+this interrupts the user experience and is not intuitive
