### ISSUE TITLE
Map Segue - Disable on Side Menu Slide Out & Fix Reloading Issue when mapView transitions to tableView

### ISSUE THREAD

**Issue by SirWellington** [BlackWholeLabs/BlackNectar-iOS#102]
# What
The segue to the Map should be disabled when the side menu is opened.

# Why
It hurts the user experience; If the side menu is open, the way you'd expect to close it is to drag it back from right to left, but right now if you do it close to the edge, it instead segues the Main View to the Map View Controller.

**Comment by cordhernandez** [comment]
+Fix issue that reloads the stores in tableView every time you transition from the mapView back to the tableView
+this interrupts the user experience and is not intuitive
