### ISSUE TITLE
Booth on Thursday

### ISSUE THREAD

**Issue by courttan** [BlackWholeLabs/BlackNectar-iOS#104]
Create fliers

Create business cards?

Create banner/signs

Create screen for monitor

**Comment by SirWellington** [comment]
Hmm we probably won't have time for business cards. 

## Here is what we CAN get

### Monitor
The iMac will be perfect for this.

### Presentation
A Brief presentation of 
+ Why are we doing this?
+ Who is BlackSource?
+ What is BlackNectar?
+ Our Vision
+ How you can help

**Comment by SirWellington** [comment]
If it's cool with you @courttan ,
I'm gonna do these in Trello, as these tickets don't really relate to the Product Development itself.

https://trello.com/b/UK0orFuL/blacknectar-kanban
