### ISSUE TITLE
Design an About Page

### ISSUE THREAD

**Issue by SirWellington** [BlackWholeLabs/BlackNectar-iOS#114]
# Requirements

## Informational
+ Copyright BlackSource
+ About BlackSource's Mission
+ Privacy Policy

## Buttons
+ Write us Feedback
+ Write us a review
+ Rate us

## Links
+ BlackSource Website
+ BlackNectar Website
+ DPSS Website
+ Project Credits

**Comment by SirWellington** [comment]
## Sketch 1
![Sketch 1.jpg](https://zube.io/files/blacksourcelabs/55d5991135d48233cab9933a626a8b96.jpeg)

**Comment by SirWellington** [comment]
## Sketch 2
![Sketch 2.jpg](https://zube.io/files/blacksourcelabs/9f11bd5cabb9218bd1b2141124c8f93c.jpeg)

**Comment by SirWellington** [comment]
## Sketch 3

![Sketch 3.jpg](https://zube.io/files/blacksourcelabs/ae3b9c936658b0c7999727e452e70c0d.jpeg)

**Comment by SirWellington** [comment]
I like some elements of each. Gonna cherry pick in the mockup-phase.

**Comment by SirWellington** [comment]
# Option 1
![5.png](https://zube.io/files/blacksourcelabs/63d947b31c2b902c2a85880db1316ed1.png)

**Comment by SirWellington** [comment]
# Option 2

![6.png](https://zube.io/files/blacksourcelabs/3b081d923f40fad6a3d5f23be9502f6f.png)

**Comment by SirWellington** [comment]
# Option  3

![7.png](https://zube.io/files/blacksourcelabs/4ed2a3d008eeeac567a97d3736839797.png)

**Comment by SirWellington** [comment]
# Option 4

![8.png](https://zube.io/files/blacksourcelabs/883e229fb189cb54c029e4869b9b8682.png)

**Comment by cordhernandez** [comment]
So far I like Option 3

**Comment by SirWellington** [comment]
Got feedback from Courtney @courttan  that will require a redesign:

```txt
there's more than two tasks at hand. I'd pare it down, maybe separate these actions?

When you say engage with the app itself, do you mean go back on the app and use it to do their thing? Or engage in the app store or online? (I'm assuming the latter)

Here's my list of priority of actions for the user: 
1. Info/Benefits - I'm assuming that's more likely why the user would go on there. 
2. Relaunch onboarding, if you have that. 
3. Social media engagement
4. Reviews/Feedback
5. About us - I think that this shouldn't be the top focus, as it will make users think you are spam. Norman Nielsen did a report on it, here's a good take-away that applies to web but I think in simplification can be applied to mobile: https://www.nngroup.com/articles/about-us-summaries/

I'd say with the iterations you have attached, I'd go with someone with a black/dark background - the contrast will make it easier to see. 
Also I'd take off the logo, it takes up too much real estate.
Liking the honeycomb thing.
```

**Comment by cordhernandez** [comment]
cool sounds like some good feedback

**Comment by SirWellington** [comment]
# Updated

## Main
![Main.png](https://zube.io/files/blacksourcelabs/96ce70cd99267b283215ccd7458ae3f4.png)

## Rate Us
![Rate-Us.png](https://zube.io/files/blacksourcelabs/87dbd944206ec61671f3d51f1d133a7e.png)

## Give Feedback
![Give-Feedback.png](https://zube.io/files/blacksourcelabs/1aca744dab1ab2f58f2c13c7bcae6dbd.png)

## Share
![Share.png](https://zube.io/files/blacksourcelabs/90ac56bbbe4e712a45e3b4b8e6c93e15.png)

**Comment by SirWellington** [comment]
@cordhernandez  Have a looksie and gimme a :thumbsup:  or :thumbsdown:

**Comment by SirWellington** [comment]
Moving this to done.

**Comment by SirWellington** [comment]
I still need to design the Benefits screen though.
