### ISSUE TITLE
Implement the My Location and Use Zip Code Switches

### ISSUE THREAD

**Issue by cordhernandez** [BlackWholeLabs/BlackNectar-iOS#145]
Code that shit...

**Comment by cordhernandez** [comment]
Make sure to customize the UI for the switches as well 
Look at the design

**Comment by cordhernandez** [comment]
+ the My Location switch is on by default which updates the map to the user's current location
+ the user can switch to enter a zip code instead 
+ the Use Zip Code switch opens up an alert view for the user to enter a zip Code 
+ write logic to make sure it's a proper zip code
+ When user enters zip code that zip code is displayed in the UI 
+ The map also moves to that zip code and reloads

**Comment by cordhernandez** [comment]
+ Also make sure to add User Preferences Code for both switches

**Comment by SirWellington** [comment]
Here are some helpful tips on creating a custom Swith:
http://plavatvornica.com/making-custom-uiswitch-part-1/

**Comment by SirWellington** [comment]
Here's a second:
http://www.c4ios.com/tutorials/customizing-switch/
