### ISSUE TITLE
Remove Custom Distance and Set Default Distance to 10 miles

### ISSUE THREAD

**Issue by cordhernandez** [BlackWholeLabs/BlackNectar-iOS#152]
+ We're no longer using a distance slider in our filter 
+ The backend will handle the default distance value
+ the app will display stores within the default value, according to the backend

**Comment by SirWellington** [comment]
Can we change this? Try just not specifying a distance. The backend will handle the default value. This allows us to change and update it more frequently.  

Wellington
Founder
BlackSource




On Thu, Feb 9, 2017 at 10:35 PM -0800, "Dero" <notifications@github.com> wrote:











We're no longer using a distance slider in our filter
The default distance will be set to 10 miles
the app will display stores within a 10 mile radius at all times

**Comment by cordhernandez** [comment]
Sure thing I'll make sure to update accordingly

**Comment by cordhernandez** [comment]
This issue has been updated 
+ The backend will handle the default distance value
+ The app will display stores within the default value, according to the backend
