### ISSUE TITLE
Add Large Loading Indicator

### ISSUE THREAD

**Issue by SirWellington** [BlackWholeLabs/BlackNectar-iOS#182]
WHY
- Currently the loading indicator is small and kind of hidden from the user
- It can be confusing on what's happening to the user if they don't see the current loading indicator 

WHAT
- keep the current loading indicator just add a bigger one to go with it 
- preferably one that is large and easily visible

**Comment by SirWellington** [comment]
Remember [this](https://github.com/ninjaprox/NVActivityIndicatorView)?

Peep it out.

**Comment by cordhernandez** [comment]
ahh yeah nice!

**Comment by SirWellington** [comment]
Removing from "View Balance Epic", since it has nothing to do with it.
