### ISSUE TITLE
Fix labels in the main TableVC

### ISSUE THREAD

**Issue by cordhernandez** [BlackWholeLabs/BlackNectar-iOS#41]
fix the labels in the cells that display the store name, address, etc

**Comment by SirWellington** [comment]
It's a little vague; can you describe what you mean.

**Comment by cordhernandez** [comment]
the text for the storeHours label gets cut off
the text for the storeAddress label gets cut off and varies in font sizes, it should stay consistent

implementing a temporary fix until Courtney takes a look at this issue
