### ISSUE TITLE
Website Prototype

### ISSUE THREAD

**Issue by SirWellington** [BlackWholeLabs/BlackNectar-iOS#92]
After we have a design for the web-site, we can use either [Wix](http://www.wix.com/) or [Google Sites](https://sites.google.com/a/redroma.tech).

**Comment by courttan** [comment]
For prototype, is this going to have features like the app? Or just a splash page?

**Comment by SirWellington** [comment]
Informational is perfect for now 😊

Wellington
Founder
BlackSource




On Fri, Jan 13, 2017 at 10:29 AM -0800, "courttan" <notifications@github.com> wrote:












For prototype, is this going to have features like the app? Or just a splash page?
